apiVersion: v1
kind: Secret
metadata:
    name: storage-configuration
    namespace: minio
stringData:
    config.env: ENC[AES256_GCM,data:N4Xq+V74qPczmIQtPg5w4rNGOvVhU1rsW71Bk1uu9T/huGDwAPt5EzbGIiKIxXQNyAYW+vp35nnIUtTXneRHFzKKqgQfefgb66NuUH86T57Z78PejL4xBURUwJIyNY54oInu7bqMch5b+T5vhq2ndFcLuJK3WOosDW+yGwFuSvMJQJsXO9VscOc=,iv:0DYtM2kAFhz9EtzaR5dcK5wGRCESxeFHFAOvQrjGtoM=,tag:qdTbHM//tmWywppcOC+xJg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1k3tuxz4t0lk43uu7za829wh2etk78g70ljel3ut3a9uavwegks9qszezph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSnJUWjFRQUJmMlpNUkdY
            aHNsTVNYU1dtcUU4eXJ6d01LL3ViTXlQNFhRCk56WGIrbGdxYUd2Qm5vZGg5VU80
            UGNEbjErVlBKb1p1YTFCMEEwM3NrN0kKLS0tIFFOZWtzMmFIYU5ZNnFzSE5YNGNW
            TGlFSVg1OVBYLytNNXhvN3J6Q3VCWWcKALqxcx7ae2amu8132sF+MuWa5nSWAT+3
            m8oSRiF6ZHdi3MJxTO3XkerIgDuOsFdgd/p2jUP99y6In+il8s5hzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T10:05:05Z"
    mac: ENC[AES256_GCM,data:h34+WEUJNOo+eDtrgTEutNOhtu5INyb8v5y8mfmOi9reF3aDOWCbTaGcCffFLLDyrG7wnRa/dUZ8IM7Z2XfuovJRWJi5xKkDR5d0l8XiJj4uDj6qOvxHKEUNscVoLxTOpVVD5pSVl0XIorwHmazR5HtCAaUbgUATHhPvWnKcZcA=,iv:7oOE6dLtN9URkbnd9cwLzA1h+o0n5chyRuPR4sboceY=,tag:tJHjy3K1uRo1ote2C0GT6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: storage-user
    namespace: minio
stringData:
    CONSOLE_ACCESS_KEY: ENC[AES256_GCM,data:+DCrSES5u6O4foB/BMsO,iv:b5FXXJDYXR4/2ko3BqegCJp9ZQL8vn54zfsj55/sA5Y=,tag:krSEZ4LnX7qv9tPH8v42sg==,type:str]
    CONSOLE_SECRET_KEY: ENC[AES256_GCM,data:/IzEO2V3u2Hw,iv:4OrzZLpwGvqTdnHxssHeph61SlBEHH8nz7oUvpTeSMw=,tag:wYElv90ajF1SutVEoU5M8Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1k3tuxz4t0lk43uu7za829wh2etk78g70ljel3ut3a9uavwegks9qszezph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSnJUWjFRQUJmMlpNUkdY
            aHNsTVNYU1dtcUU4eXJ6d01LL3ViTXlQNFhRCk56WGIrbGdxYUd2Qm5vZGg5VU80
            UGNEbjErVlBKb1p1YTFCMEEwM3NrN0kKLS0tIFFOZWtzMmFIYU5ZNnFzSE5YNGNW
            TGlFSVg1OVBYLytNNXhvN3J6Q3VCWWcKALqxcx7ae2amu8132sF+MuWa5nSWAT+3
            m8oSRiF6ZHdi3MJxTO3XkerIgDuOsFdgd/p2jUP99y6In+il8s5hzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T10:05:05Z"
    mac: ENC[AES256_GCM,data:h34+WEUJNOo+eDtrgTEutNOhtu5INyb8v5y8mfmOi9reF3aDOWCbTaGcCffFLLDyrG7wnRa/dUZ8IM7Z2XfuovJRWJi5xKkDR5d0l8XiJj4uDj6qOvxHKEUNscVoLxTOpVVD5pSVl0XIorwHmazR5HtCAaUbgUATHhPvWnKcZcA=,iv:7oOE6dLtN9URkbnd9cwLzA1h+o0n5chyRuPR4sboceY=,tag:tJHjy3K1uRo1ote2C0GT6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-user-secrets
    namespace: minio
stringData:
    SUDOKU_ACCESS_KEY: ENC[AES256_GCM,data:u2DLWzYb,iv:F8pF6T/NtYF+WvpMiE5Q60rg87F7UJ10tQwRH49/H/Q=,tag:3fEAoViG6C2xHaL8qvc72A==,type:str]
    SUDOKU_SECRET_KEY: ENC[AES256_GCM,data:Uz0F7sflxtEwdIw=,iv:Cvwxw7R3Ta/ZL0+6Jm++MY20UzZ4saQjqYLzpxblFyA=,tag:y9TFVypBF1nWJsdlWC7YYA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1k3tuxz4t0lk43uu7za829wh2etk78g70ljel3ut3a9uavwegks9qszezph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSnJUWjFRQUJmMlpNUkdY
            aHNsTVNYU1dtcUU4eXJ6d01LL3ViTXlQNFhRCk56WGIrbGdxYUd2Qm5vZGg5VU80
            UGNEbjErVlBKb1p1YTFCMEEwM3NrN0kKLS0tIFFOZWtzMmFIYU5ZNnFzSE5YNGNW
            TGlFSVg1OVBYLytNNXhvN3J6Q3VCWWcKALqxcx7ae2amu8132sF+MuWa5nSWAT+3
            m8oSRiF6ZHdi3MJxTO3XkerIgDuOsFdgd/p2jUP99y6In+il8s5hzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T10:05:05Z"
    mac: ENC[AES256_GCM,data:h34+WEUJNOo+eDtrgTEutNOhtu5INyb8v5y8mfmOi9reF3aDOWCbTaGcCffFLLDyrG7wnRa/dUZ8IM7Z2XfuovJRWJi5xKkDR5d0l8XiJj4uDj6qOvxHKEUNscVoLxTOpVVD5pSVl0XIorwHmazR5HtCAaUbgUATHhPvWnKcZcA=,iv:7oOE6dLtN9URkbnd9cwLzA1h+o0n5chyRuPR4sboceY=,tag:tJHjy3K1uRo1ote2C0GT6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
